const scope = [
	"bold",
	"comment",
	"comment.block.documentation entity.name.type.instance",
	"comment.block.documentation keyword",
	"comment.block.documentation markup.inline.raw.string.markdown",
	"comment.block.documentation markup",
	"comment.block.documentation punctuation",
	"comment.block.documentation punctuation.definition.block.tag",
	"comment.block.documentation storage",
	"comment.block.documentation storage.type",
	"comment.block.documentation support",
	"comment.block.documentation variable",
	"comment.block.documentation",
	"constant.character.escape.backslash",
	"constant.character.escape",
	"constant.character",
	"constant.escape",
	"constant.language",
	"constant.numeric",
	"constant.other.caps",
	"constant.other.character-class.regexp",
	"constant.other.character-class.set.regexp",
	"constant.other.color.rgb-value.hex punctuation.definition.constant",
	"constant.other.color",
	"constant.other.key",
	"constant.other.php",
	"constant.other.reference.link.markdown",
	"constant.other.symbol",
	"constant.other",
	"constant.regexp",
	"constant.sha.git-rebase",
	"emphasis",

	"entity.name.class",
	"entity.name.function.blade",
	"entity.name.function.preprocessor",
	"entity.name.function",
	"entity.name.method.js",
	"entity.name.module.js",
	"entity.name.namespace",
	"entity.name.operator",
	"entity.name.operator.custom-literal",
	"entity.name.scope-resolution",
	"entity.name.tag support.class.component",
	"entity.name.tag.css",
	"entity.name.tag.less",
	"entity.name.tag.reference",
	"entity.name.tag",
	"entity.name.type.hcl",
	"entity.name.type",
	"entity.name",
	"entity.other.attribute",
	"entity.other.attribute-name.class punctuation.definition.entity",
	"entity.other.attribute-name.class.css",
	"entity.other.attribute-name.class",
	"entity.other.attribute-name.id.css",
	"entity.other.attribute-name.id.html",
	"entity.other.attribute-name.id",
	"entity.other.attribute-name.parent-selector-suffix punctuation.definition.entity.css",
	"entity.other.attribute-name.parent-selector.css",
	"entity.other.attribute-name.parent.less",
	"entity.other.attribute-name.placeholder.css punctuation.definition.entity.css",
	"entity.other.attribute-name.placeholder",
	"entity.other.attribute-name.pseudo-class punctuation.definition.entity",
	"entity.other.attribute-name.pseudo-class",
	"entity.other.attribute-name.pseudo-element punctuation.definition.entity",
	"entity.other.attribute-name.pseudo-element.css",
	"entity.other.attribute-name.pseudo-element",
	"entity.other.attribute-name.scss",
	"entity.other.attribute-name",
	"entity.other.inherited-class",
	"entity.tag.apacheconf",
	"expression.embbeded.vue punctuation.definition.tag",
	"header",
	"heading.1.markdown entity.name",
	"heading.1.markdown punctuation.definition.heading.markdown",
	"heading.2.markdown entity.name",
	"heading.2.markdown punctuation.definition.heading.markdown",
	"heading.3.markdown entity.name",
	"heading.3.markdown punctuation.definition.heading.markdown",
	"heading.4.markdown entity.name",
	"heading.4.markdown punctuation.definition.heading.markdown",
	"heading.5.markdown entity.name",
	"heading.5.markdown punctuation.definition.heading.markdown",
	"heading.6.markdown entity.name",
	"heading.6.markdown punctuation.definition.heading.markdown",
	"invalid.deprecated",
	"invalid.illegal",
	"invalid",
	"keyword.blade",
	"keyword.control punctuation.definition.keyword",
	"keyword.control.as",
	"keyword.control.at-rule.extend punctuation.definition.keyword",
	"keyword.control.at-rule.include punctuation.definition.keyword",
	"keyword.control.at-rule.mixin punctuation.definition.keyword",
	"keyword.control.default",
	"keyword.control.export",
	"keyword.control.flow.block-scalar.literal",
	"keyword.control.flow.python",
	"keyword.control.flow",
	"keyword.control.from",
	"keyword.control.import",
	"keyword.control.module.js",
	"keyword.control.return",
	"keyword.control.smarty",
	"keyword.control.twig",
	"keyword.control",
	"keyword.operator.alignas",
	"keyword.operator.alignof",
	"keyword.operator.assignment.jsdoc",
	"keyword.operator.bitwise.shift",
	"keyword.operator.bitwise",
	"keyword.operator.cast",
	"keyword.operator.comparison.twig",
	"keyword.operator.comparison",
	"keyword.operator.expression",
	"keyword.operator.instanceof",
	"keyword.operator.logical.python",
	"keyword.operator.logical",
	"keyword.operator.minus.exponent",
	"keyword.operator.new",
	"keyword.operator.noexcept",
	"keyword.operator.or.regexp",
	"keyword.operator.plus.exponent",
	"keyword.operator.quantifier.regexp",
	"keyword.operator.relational",
	"keyword.operator.rest",
	"keyword.operator.sizeof",
	"keyword.operator.spread",
	"keyword.operator.ternary",
	"keyword.operator.typeid",
	"keyword.operator.wordlike",
	"keyword.operator",
	"keyword.other.DML",
	"keyword.other.important",
	"keyword.other.phpdoc.php",
	"keyword.other.special-method",
	"keyword.other.substitution",
	"keyword.other.template",
	"keyword.other.this",
	"keyword.other.type.php",
	"keyword.other.unit",
	"keyword.other",
	"keyword",
	"log.date",
	"markup.bold markup.italic punctuation",
	"markup.bold markup.italic",
	"markup.bold punctuation",
	"markup.bold",
	"markup.changed",
	"markup.deleted",
	"markup.fenced_code.block.markdown",
	"markup.heading",
	"markup.inline.raw.string.markdown",
	"markup.inline.raw",
	"markup.inserted",
	"markup.italic punctuation",
	"markup.italic",
	"markup.quote punctuation.definition.blockquote.markdown",
	"markup.quote",
	"markup.strikethrough",
	"markup.table",
	"markup.underline punctuation",
	"markup.underline.link",
	"markup.underline",
	"meta.array.literal variable",
	"meta.at-rule.extend keyword.control.at-rule.extend",
	"meta.at-rule.function keyword.control.at-rule.function",
	"meta.at-rule.function variable.parameter.url",
	"meta.at-rule.include entity.name.function.scss",
	"meta.at-rule.include keyword.control.at-rule.include",
	"meta.at-rule.media keyword.control.at-rule.media",
	"meta.at-rule.mixin keyword.control.at-rule.mixin",
	"meta.at-rule.mixin punctuation.separator.key-value",
	"meta.at-rule.mixin.scss entity.name.function.scss",
	"meta.at-rule.return variable.parameter.url",
	"meta.attribute-selector",
	"meta.attribute.directive",
	"meta.block entity.name.label",
	"meta.block",
	"meta.brace",
	"meta.class-method.js entity.name.function.js",
	"meta.definition.method entity.name.function",
	"meta.definition.variable variable.other.constant",
	"meta.definition.variable variable.other.readwrite",
	"meta.definition.variable",
	"meta.diff.header",
	"meta.directive.vue entity.other.attribute-name.html",
	"meta.directive.vue punctuation.separator.key-value.html",
	"meta.embedded.assembly",
	"meta.embedded.block",
	"meta.embedded.inline.phpx constant.other.php",
	"meta.embedded.inline.phpx punctuation.definition.tag.begin.html",
	"meta.embedded.inline.phpx punctuation.definition.tag.end.html",
	"meta.embedded.line.tag.smarty",
	"meta.embedded",
	"meta.field.declaration.ts variable.object.property",
	"meta.fstring",
	"meta.function-call entity.name.function",
	"meta.function-call meta.function-call.arguments",
	"meta.function-call variable.other.object.property",
	"meta.function-call",
	"meta.function.parameter variable",
	"meta.function.parameters punctuation.definition.variable",
	"meta.group.braces.curly constant.other.object.key.js string.unquoted.label.js",
	"meta.import keyword.other",
	"meta.import.qualifier",
	"meta.jsx.children",
	"meta.mapping.key.hcl variable.other.readwrite.hcl",
	"meta.object-literal entity.name.function",
	"meta.object-literal.key",
	"meta.objectliteral meta.object.member meta.objectliteral meta.object.member meta.objectliteral meta.object.member meta.object-literal.key",
	"meta.object.member",
	"meta.other.type.phpdoc.php keyword.other.type.php",
	"meta.other.type.phpdoc.php punctuation.separator.inheritance.php",
	"meta.other.type.phpdoc.php support.class",
	"meta.other.type.phpdoc.php support.other.namespace.php",
	"meta.preprocessor.numeric",
	"meta.preprocessor.string",
	"meta.preprocessor",
	"meta.property-list meta.at-rule.else",
	"meta.property-list meta.at-rule.if",
	"meta.property-list meta.at-rule.include",
	"meta.property-list meta.property-list",
	"meta.property-list meta.property-value",
	"meta.property-list punctuation.separator.key-value",
	"meta.property-list",
	"meta.separator",
	"meta.structure.dictionary.key.python",
	"meta.tag JSXNested",
	"meta.tag.blade keyword.other.type.php",
	"meta.tag.custom entity.name.tag",
	"meta.tag.other.unrecognized.html.derivative entity.name.tag",
	"meta.tag.template.value.twig meta.function.arguments.twig",
	"meta.tag",
	"meta.template.expression",
	"meta.use.php",
	"meta.var.expr storage.type",
	"punctuation.definition.arguments",
	"punctuation.definition.array",
	"punctuation.definition.begin.bracket",
	"punctuation.definition.block",
	"punctuation.definition.character-class.regexp",
	"punctuation.definition.class",
	"punctuation.definition.comment",
	"punctuation.definition.constant.markdown",
	"punctuation.definition.constant",
	"punctuation.definition.dictionary",
	"punctuation.definition.end.bracket",
	"punctuation.definition.entity",
	"punctuation.definition.group.shell",
	"punctuation.definition.group",
	"punctuation.definition.keyword",
	"punctuation.definition.list_item.markdown",
	"punctuation.definition.list.begin.markdown",
	"punctuation.definition.parameters",
	"punctuation.definition.quote.begin.markdown",
	"punctuation.definition.section.switch-block.begin.bracket",
	"punctuation.definition.section.switch-block.end.bracket",
	"punctuation.definition.string",
	"punctuation.definition.switch-expression.begin.bracket",
	"punctuation.definition.switch-expression.end.bracket",
	"punctuation.definition.tag",
	"punctuation.definition.template-expression.begin",
	"punctuation.definition.template-expression.end",
	"punctuation.definition.template-expression",
	"punctuation.definition.use",
	"punctuation.section.embedded.begin.php",
	"punctuation.section.embedded.end.php",
	"punctuation.section.embedded",
	"punctuation.section.tag.twig",
	"punctuation.section",
	"punctuation.separator.inheritance.php",
	"punctuation.support.type.property-name",
	"punctuation.terminator.rule",
	"punctuation",
	"settings",
	"source.coffee.embedded",
	"source.cpp meta.block variable.other",
	"source.css entity.other.attribute-name.class",
	"source.css entity.other.attribute-name.pseudo-class",
	"source.css support.type.property-name",
	"source.css variable",
	"source.css.less entity.other.attribute-name.id",
	"source.env",
	"source.groovy.embedded",
	"source.js constant.other.object.key.js string.unquoted.label.js",
	"source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
	"source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
	"source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
	"source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
	"source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
	"source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
	"source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
	"source.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json",
	"source.json meta.structure.dictionary.json support.type.property-name.json",
	"source.less support.type.property-name",
	"source.postcss support.type.property-name",
	"source.powershell variable.other.member",
	"source.python",
	"source.sass keyword.control",
	"source.sass support.type.property-name",
	"source.stylus support.type.property-name",
	"meta.type.cast.expr",
	"meta.type.new.expr",
	"support.constant.math",
	"support.constant.dom",
	"variable",
	"entity.name.label",
	"punctuation.definition.group.regexp",
				"punctuation.definition.group.assertion.regexp",
				"punctuation.definition.character-class.regexp",
				"punctuation.character.set.begin.regexp",
				"punctuation.character.set.end.regexp",
				"keyword.operator.negation.regexp",
				"support.other.parenthesis.regexp",
	"constant.character.character-class.regexp",
				"constant.other.character-class.set.regexp",
				"constant.other.character-class.regexp",
				"constant.character.set.regexp",
				"keyword.operator.or.regexp",
				"keyword.control.anchor.regexp",
				"constant.character",
				"constant.other.option",
	"support.constant.property-value",
				"support.constant.font-name",
				"support.constant.media-type",
				"support.constant.media",
				"constant.other.color.rgb-value",
				"constant.other.rgb-value",
				"support.constant.color",
				"meta.definition.variable.name",
				"support.variable",
				"entity.name.variable",
				"constant.other.placeholder",
				"source.cpp keyword.operator.new",
				"keyword.operator.delete",
				"keyword.operator.new",
				"keyword.other.using",
				"keyword.other.directive.using",
				"keyword.other.operator",
				"entity.name.operator",
	"support.constant.json",
	"punctuation.separator.namespace.ruby",
	"storage.modifier.async",
	"storage.modifier.import.java",
	"storage.modifier.package.java",
	"storage.modifier",
	"storage.type.numeric.go",
	"storage.type.byte.go",
	"storage.type.boolean.go",
	"storage.type.string.go",
	"storage.type.uintptr.go",
	"storage.type.error.go",
	"storage.type.rune.go",
	"storage.type.generic.cs",
	"storage.type.modifier.cs",
	"storage.type.variable.cs",
	"storage.type.annotation.java",
	"storage.type.generic.java",
	"storage.type.java",
	"storage.type.object.array.java",
	"storage.type.primitive.array.java",
	"storage.type.primitive.java",
	"storage.type.token.java",
	"storage.type.groovy",
	"storage.type.annotation.groovy",
	"storage.type.parameters.groovy",
	"storage.type.generic.groovy",
	"storage.type.object.array.groovy",
	"storage.type.primitive.array.groovy",
	"storage.type.primitive.groovy",
	"storage.type.cs",
	"storage.type.function",
	"storage.type.php",
	"storage.type",
	"storage",
	"string constant.character",
	"string constant.other.placeholder",
	"string meta.image.inline.markdown",
	"string.alias.graphql",
	"string.other.link.description.title.markdown",
	"string.other.link",
	"string.quoted.docstring.multi.python constant.character.escape",
	"string.quoted.docstring.multi.python punctuation.definition.string.begin",
	"string.quoted.docstring.multi.python punctuation.definition.string.end",
	"string.quoted.docstring.multi",
	"string.regexp",
	"string.tag",
	"string.unquoted.alias.graphql",
	"string.unquoted.graphql",
	"string.value",

	/**string. */
	"string",
	
	"strong",
	"support.class",
	"support.constant.font-name",
	"support.constant.handlebars keyword.control",
	"support.constant.handlebars",
	"support.constant",
	"support.function.git-rebase",
	"support.function",
	"support.orther.namespace.use.php",
	"support.other.namespace.php",
	"support.other.variable",
	"support.type.map.key",
	"support.type.object.module",
	"support.type.property-name.css",
	"support.type.property-name",
	"support.type.sys-types",
	"support.type.vendored.property-name",
	"support.type",
	"support.variable.dom",
	"support.variable.property.dom",
	"support.variable.property",
	"support.variable",
	"tag.decorator.js entity.name.tag.js",
	"tag.decorator.js punctuation.definition.tag.js",
	"text.html constant.character.entity",
	"text.html.basic entity.other.attribute-name.html",
	"text.html.basic entity.other.attribute-name",
	"text.html.markdown markup.inline.raw.markdown punctuation.definition.raw.markdown",
	"text.html.markdown markup.inline.raw.markdown",
	"text.html.php meta.embedded.block.html meta.tag.metadata.script.end.html punctuation.definition.tag.begin.html text.html.basic",
	"text.html.twig meta.tag.inline.any.html",
	"text.html.vue-html meta.tag",
	"text.html",
	"text.log",
	"token.debug-token",
	"token.error-token",
	"token.info-token",
	"token.warn-token",
	"variable.declaration.hcl variable.other.readwrite.hcl",
	"variable.function.constructor",
	"variable.function",
	"variable.import.parameter.js",
	"variable.language.fenced.markdown",
	"variable.language.this punctuation.definition.variable",
	"variable.language.wildcard.java",
	"variable.language",
	"variable.legacy.builtin.python",
	"variable.other punctuation.definition.variable",
	"variable.other.class.js",
	"variable.other.constant.object",
	"variable.other.constant",
	"variable.other.declaration",
	"variable.other.enummember",
	"variable.other.global punctuation.definition.variable",
	"variable.other.global.safer punctuation.definition.variable",
	"variable.other.global.safer",
	"variable.other.global",
	"variable.other.object.property",
	"variable.other.object",
	"variable.other.property",

	/**let hogeData = somehoge.execute() */
	"variable.other.readwrite",

	"variable.other.readwrite.alias",
	"variable.parameter.function.language.special",
	"variable.parameter.handlebars",
	"variable.parameter",
    "keyword.control.default",
    "keyword.control.export",
    "keyword.control.from",
    "keyword.control.import",
    "keyword.operator.bitwise.shift",
    "keyword.other",
    "meta.at-rule.function variable.parameter.url",
    "meta.at-rule.mixin punctuation.separator.key-value",
    "meta.embedded.inline.phpx punctuation.definition.tag.begin.html",
    "meta.embedded.inline.phpx punctuation.definition.tag.end.html",
    "string.quoted.docstring.multi.python constant.character.escape",
    "string.quoted.docstring.multi.python punctuation.definition.string.begin",
    "string.quoted.docstring.multi.python punctuation.definition.string.end",
    "variable.parameter",
	"keyword.operator.assignment"
] as const;	
const semantic = [
    "*.defaultLibrary",
	"enumMember",
    "property.declaration",
    "property.defaultLibrary",
	"parameter",
	"parameter.declaration",
	"variable.constant",
    "variable.declaration",
    "variable.defaultLibrary",
] as const;
export type Scopes = (typeof scope)[number]
export type Semantics = (typeof semantic)[number]